### ISSUE TITLE
Align flow-go-sdk with latest Access API changes

### ISSUE THREAD

**Issue by peterargue** [onflow/flow-go-sdk#735]
There have been a number of changes and new additions to the Access API in recent months. This epic covers the work needed to bring the SDK up to date with flow-go.
```[tasklist]
### Tasks
- [ ] https://github.com/onflow/flow-go-sdk/issues/741
- [ ] https://github.com/onflow/flow-go-sdk/issues/750
- [ ] https://github.com/onflow/flow-go-sdk/issues/752
- [ ] https://github.com/onflow/flow-go-sdk/issues/736
- [ ] https://github.com/onflow/flow-go-sdk/issues/744
- [ ] https://github.com/onflow/flow-go-sdk/issues/745
- [ ] https://github.com/onflow/flow-go-sdk/issues/746
- [ ] https://github.com/onflow/flow-go-sdk/issues/747
- [ ] https://github.com/onflow/flow-go-sdk/issues/748
- [ ] https://github.com/onflow/flow-go-sdk/issues/749
- [ ] https://github.com/onflow/flow-go-sdk/issues/751
- [ ] Add new fields to NodeVersionInfo https://github.com/onflow/flow/pull/1496
```
